version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
    volumes:
      - model_cache:/app/cache

  frontend:
    build: ./frontend/help-bubble-ui
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  model_cache:
